Update contactus.html
Moz-NIEC/Site-on pull request #3
Opened 2018-10-02 16:37 UTC by Sumindar

some updations.

2018-10-02 19:03 UTC, suhailsinghbains requested changes

2018-10-02 19:03 UTC, suhailsinghbains commented on contactus.html
> +            <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.This is a promise.</small>
Please add a white-space between '.' & 'T'

2018-10-02 19:03 UTC, suhailsinghbains commented on contactus.html
> +                errorMessage += "<p>Your email address is not valid.PLease try again.</p>"
Please add a white-space between '.' & 'P'
Replace 'L'  to 'l' in 'PLease'

2018-10-02 19:05 UTC, suhailsinghbains commented
Thanks for the PR, I have suggested some changes, please make those, feel free to ask here for any queries.

2018-10-04 16:12 UTC, Sumindar commented
Ok thanks sir

2018-10-04 16:42 UTC, suhailsinghbains commented
Hi,
LGTM, thanks for the effort made!
Please Edit this [comment](https://github.com/Moz-NIEC/Site-on/pull/3#issuecomment-427078430) and remove "Sir". Please don't call "Sir" or "Ma'am" in the open-source community. Always refer to people by either using IRC Nick or First Name.
I'll merge once you edit the comment.
Great work though :)

2018-10-05 16:47 UTC, Sumindar commented
Hi,
I am a beginner in open source,so kindly guide me as to how contribute more
and more to the open source.
Thanks a lot.

On Thu, Oct 4, 2018, 10:12 PM Suhail Singh Bains <notifications@github.com>
wrote:

> Hi,
> LGTM, thanks for the effort made!
> Please Edit this comment
> <https://github.com/Moz-NIEC/Site-on/pull/3#issuecomment-427078430> and
> remove "Sir". Please don't call "Sir" or "Ma'am" in the open-source
> community. Always refer to people by either using IRC Nick or First Name.
> I'll merge once you edit the comment.
> Great work though :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Moz-NIEC/Site-on/pull/3#issuecomment-427088545>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AfDY5CdMUaJqDx8GYJv-vbdlXagJf-sNks5uhjqQgaJpZM4XEavm>
> .
>

2018-10-06 07:38 UTC, suhailsinghbains approved these changes

2018-10-06 07:41 UTC, suhailsinghbains commented
I feel @championshuttler can guide you better. This is his [Telegram](https://t.me/championshuttler )

2018-10-06 07:42 UTC, merged